# Generated by Rovo Dev
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MachineProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("units", models.CharField(choices=[("mm", "Millimeters"), ("in", "Inches")], default="mm", max_length=4)),
                ("origin", models.CharField(choices=[("front_left", "Front-Left (0,0)"), ("center", "Center")], default="front_left", max_length=16)),
                ("bed_width", models.FloatField(default=210.0, help_text="Bed width in units")),
                ("bed_height", models.FloatField(default=297.0, help_text="Bed height in units")),
                ("travel_feedrate", models.FloatField(default=3000.0, help_text="Travel feedrate (units/min)")),
                ("draw_feedrate", models.FloatField(default=1500.0, help_text="Draw feedrate (units/min)")),
                ("z_up", models.FloatField(default=5.0)),
                ("z_down", models.FloatField(default=0.0)),
                ("preamble", models.TextField(default='; Vectra preamble\nG90 ; absolute positioning\nG21 ; units in mm (if applicable)\n')),
                ("postamble", models.TextField(default='; Vectra postamble\nM2 ; program end\n')),
            ],
        ),
    ]
