# Generated by Rovo Dev
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("machines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machineprofile",
            name="tool_change_template",
            field=models.TextField(default='; --- Tool change ---\nM117 Change pen to {tool_name}\nM0 Change pen to {tool_name}\n', help_text="G-code inserted when changing tools. Available placeholders: {tool_name}"),
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("color_hex", models.CharField(default="#000000", max_length=7)),
                ("width_mm", models.FloatField(default=0.3)),
                ("z_down_override", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tools", to="machines.machineprofile"),
                ),
            ],
            options={"unique_together": {("profile", "name")}},
        ),
    ]
