# Generated by Rovo Dev
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pipelines", to="projects.project"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PipelineStepModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField()),
                ("type", models.CharField(max_length=64)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "pipeline",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="pipeline.pipeline"),
                ),
            ],
            options={"ordering": ["order", "id"], "unique_together": {("pipeline", "order")}},
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed")], default="pending", max_length=16)),
                ("error", models.TextField(blank=True)),
                ("steps_snapshot", models.JSONField(default=list)),
                ("steps_executed", models.JSONField(default=list)),
                ("duration_ms", models.PositiveBigIntegerField(default=0)),
                (
                    "asset",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pipeline_runs", to="projects.asset"),
                ),
                (
                    "pipeline",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="pipeline.pipeline"),
                ),
                (
                    "started_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("svg", "SVG"), ("gcode", "G-code"), ("png", "PNG"), ("log", "Log")], max_length=16)),
                ("file", models.FileField(upload_to="pipeline_runs/%Y/%m/%d")),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="pipeline.pipelinerun"),
                ),
            ],
        ),
    ]
