# Generated by Rovo Dev
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="assets/%Y/%m/%d")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("svg", "SVG"), ("pdf", "PDF"), ("png", "PNG"), ("jpg", "JPG"), ("other", "Other")],
                        max_length=10,
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assets", to="projects.project"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(blank=True, related_name="collaborations", to=settings.AUTH_USER_MODEL),
        ),
    ]
